apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-store
  namespace: secrets-aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Use Terraform output: eso_role_arn
      role: arn:aws:iam::123456789012:role/ra-eso-aws-secrets-reader
      auth:
        jwt:
          serviceAccountRef:
            name: eso-aws-auth
