apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: raycluster-pvc
 namespace: default
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Ti
 storageClassName: shared-vast
