apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: secrets-gcp
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secretsmanager-store
    kind: SecretStore
  target:
    name: app-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: ra-demo-db-username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ra-demo-db-password
    - secretKey: API_TOKEN
      remoteRef:
        key: ra-demo-api-token
