{{- if .Values.prometheus.externalAccess.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: prometheus-tls
  dnsNames:
    - prometheus.{{ .Values.orgID }}-{{ .Values.clusterName }}.coreweave.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  usages:
    - server auth
    - digital signature
    - key encipherment
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-auth
  namespace: {{ .Release.Namespace }}
spec:
  basicAuth:
    secret: prometheus-auth-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  users: |
    {{ .Values.prometheus.externalAccess.credentials }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.{{ .Values.orgID }}-{{ .Values.clusterName }}.coreweave.app`)
      kind: Rule
      services:
        - name: prometheus-operated
          port: 9090
      middlewares:
        - name: prometheus-auth
  tls:
    secretName: prometheus-tls
{{- end }}