{{- if and .Values.caiosAccessKey .Values.caiosSecretKey not .Values.existingCaiosSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cw-dragonfly.caiosSecretName" . }}
type: Opaque
stringData:
  accesskey: {{ .Values.caiosAccessKey }}
  secretkey: {{ .Values.caiosSecretKey }}
---
{{- end }}
{{- if not .Values.existingDbPasswordSecretName -}}
{{- $dbPasswordSecretName := ( include "cw-dragonfly.dbPasswordSecretName" . ) -}}
{{- $dbPasswordSecret := ( lookup "v1" "Secret" .Release.Namespace $dbPasswordSecretName ) -}}
{{- $password := "" }}
{{- if and $dbPasswordSecret (not .Values.dbPassword) }}
  {{- $password = index $dbPasswordSecret.data "password" | b64dec }}
{{- else if .Values.dbPassword }}
  {{- $password = .Values.dbPassword }}
{{- else }}
  {{- $password = randAlphaNum 20 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dbPasswordSecretName }}
type: Opaque
stringData:
  password: {{ $password }}
{{- end }}
