apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sunk

helmCharts:
  - name: sunk
    repo: http://helm.corp.ingress.ord1.coreweave.com
    version: "7.4.1"
    releaseName: sunk
    valuesFile: values.yaml
    namespace: sunk
