apiVersion: batch/v1
kind: Job
metadata:
  name: gcs-to-caios-copy
  namespace: data-migration
spec:
  completions: 32            # = number of shards
  parallelism: 8             # = how many run at once (pods)
  completionMode: Indexed
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: rclone
        image: rclone/rclone:latest
        resources:
          requests:
            cpu: "16"
            memory: "128Gi"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: JOB_INDEX               # handy for logs
          value: "$(JOB_COMPLETION_INDEX)"
        - name: SHARDS_BUCKET               # handy for logs
          value: <your_shards_bucket_name_here>
        - name: SOURCE_BUCKET               # handy for logs
          value: <your_source_bucket_name_here>
        - name: DESTINATION_BUCKET               # handy for logs
          value: <your_destination_bucket_name_here>

        command: ["/bin/sh", "-c"]
        args:
        - |
          set -euo pipefail

          ## NOTE: Change the shard format to shard_%03d if you use more than 99 shards
          SHARD=$(printf "shard_%02d" ${JOB_COMPLETION_INDEX})
          echo "[$(date)] Copying list $SHARD"

          # Pull the manifest line-list into the pod
          rclone --config /etc/rclone/rclone.conf \
                  cat caios:$SHARDS_BUCKET/shards/$SHARD > /work/$SHARD

          cat /work/$SHARD
          # Main copy pass
          rclone --config /etc/rclone/rclone.conf                           \
                 copy gcs:$SOURCE_BUCKET caios:$DESTINATION_BUCKET          \
                 --files-from /work/$SHARD                                  \
                 --transfers 64 --checkers 128                              \
                 --s3-chunk-size 100M --s3-upload-concurrency 12            \
                 --multi-thread-streams 8 --multi-thread-cutoff 64M         \
                 --progress --stats 30s

          echo "[$(date)] DONE with $SHARD"

        volumeMounts:
        - mountPath: /etc/rclone
          name: rclone-config
          readOnly: true
        - mountPath: /var/secrets/google
          name: gcs-sa
          readOnly: true
        - mountPath: /work              # scratch space for the shard file
          name: work

      volumes:
      - name: rclone-config
        secret:
          secretName: rclone-config
      - name: gcs-sa
        secret:
          secretName: gcs-service-account
      - name: work
        emptyDir: {}
