apiVersion: v1
kind: Secret
metadata:
  name: infisical-kubernetes-auth
  namespace: secrets-infisical
type: Opaque
stringData:
  # Machine Identity ID configured in Infisical Kubernetes Auth.
  identityId: "<REPLACE_INFISICAL_MACHINE_IDENTITY_ID>"
