apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-store
  namespace: secrets-infisical
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        kubernetesAuthCredentials:
          identityId:
            name: infisical-kubernetes-auth
            key: identityId
      secretsScope:
        projectSlug: "<REPLACE_INFISICAL_PROJECT_SLUG>"
        environmentSlug: "dev"
        secretsPath: "/"
