apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: secrets-infisical
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-store
    kind: SecretStore
  target:
    name: app-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: API_TOKEN
      remoteRef:
        key: API_TOKEN
