{{- if .Values.prometheus.enabled }}
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "vllm-basic.name" . }}
  labels:
    app: {{ include "vllm-basic.name" . }}
spec:
  endpoints:
  - targetPort: {{ .Values.vllm.port.containerPort }}
    path: /metrics
  selector:
    matchLabels:
      app: {{ include "vllm-basic.name" . }}
---
{{- end }}
