apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-basic.fullname" . }}
  {{- if .Values.service.public }}
  annotations:
    service.beta.kubernetes.io/coreweave-load-balancer-type: public
    service.beta.kubernetes.io/external-hostname: {{ include "vllm-basic.service.hostname" . }}
  {{- end }}
  labels:
    app: {{ include "vllm-basic.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.port }}
      targetPort: {{ .Values.vllm.port.containerPort }}
      protocol: {{ .Values.service.port.protocol }}
      name: {{ .Values.service.port.name }}
  selector:
    {{- if eq .Values.vllm.workload.type "deployment" }}
    app: {{ include "vllm-basic.name" . }}
    {{- else if eq .Values.vllm.workload.type "leaderWorkerSet" }}
    role: leader
    leaderworkerset.sigs.k8s.io/name: {{ include "vllm-basic.fullname" . }}
    {{- end }}
